version: 2
updates:
  # Monitora dependências do Gradle (bibliotecas, plugins e wrapper)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily" # Verifica atualizações todos os dias (limite máximo nativo do Dependabot)
    open-pull-requests-limit: 5

  # Monitora dependências dos workflows do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily" # Verifica todos os dias
    open-pull-requests-limit: 5
